export default [
  {
    id: 1,
    cname: '阿富汗',
    ename: 'Afghanistan',
    phone_code: '+93',
  },
  {
    id: 2,
    cname: '奥兰群岛',
    ename: 'Aland Islands',
    phone_code: '+358-18',
  },
  {
    id: 3,
    cname: '阿尔巴尼亚',
    ename: 'Albania',
    phone_code: '+355',
  },
  {
    id: 4,
    cname: '阿尔及利亚',
    ename: 'Algeria',
    phone_code: '+213',
  },
  {
    id: 5,
    cname: '美属萨摩亚群岛',
    ename: 'American Samoa',
    phone_code: '+1-684',
  },
  {
    id: 6,
    cname: '安道尔',
    ename: 'Andorra',
    phone_code: '+376',
  },
  {
    id: 7,
    cname: '安哥拉',
    ename: 'Angola',
    phone_code: '+244',
  },
  {
    id: 8,
    cname: '安圭拉',
    ename: 'Anguilla',
    phone_code: '+1-264',
  },
  {
    id: 9,
    cname: '南极洲',
    ename: 'Antarctica',
    phone_code: '+672',
  },
  {
    id: 10,
    cname: '安提瓜和巴布达',
    ename: 'Antigua And Barbuda',
    phone_code: '+1-268',
  },
  {
    id: 11,
    cname: '阿根廷',
    ename: 'Argentina',
    phone_code: '+54',
  },
  {
    id: 12,
    cname: '阿美尼亚',
    ename: 'Armenia',
    phone_code: '+374',
  },
  {
    id: 13,
    cname: '阿鲁巴',
    ename: 'Aruba',
    phone_code: '+297',
  },
  {
    id: 14,
    cname: '澳大利亚',
    ename: 'Australia',
    phone_code: '+61',
  },
  {
    id: 15,
    cname: '奥地利',
    ename: 'Austria',
    phone_code: '+43',
  },
  {
    id: 16,
    cname: '阿塞拜疆',
    ename: 'Azerbaijan',
    phone_code: '+994',
  },
  {
    id: 17,
    cname: '巴哈马',
    ename: 'Bahamas The',
    phone_code: '+1-242',
  },
  {
    id: 18,
    cname: '巴林',
    ename: 'Bahrain',
    phone_code: '+973',
  },
  {
    id: 19,
    cname: '孟加拉国',
    ename: 'Bangladesh',
    phone_code: '+880',
  },
  {
    id: 20,
    cname: '巴巴多斯',
    ename: 'Barbados',
    phone_code: '+1-246',
  },
  {
    id: 21,
    cname: '白俄罗斯',
    ename: 'Belarus',
    phone_code: '+375',
  },
  {
    id: 22,
    cname: '比利时',
    ename: 'Belgium',
    phone_code: '+32',
  },
  {
    id: 23,
    cname: '伯利兹',
    ename: 'Belize',
    phone_code: '+501',
  },
  {
    id: 24,
    cname: '贝宁',
    ename: 'Benin',
    phone_code: '+229',
  },
  {
    id: 25,
    cname: '百慕大群岛',
    ename: 'Bermuda',
    phone_code: '+1-441',
  },
  {
    id: 26,
    cname: '不丹',
    ename: 'Bhutan',
    phone_code: '+975',
  },
  {
    id: 27,
    cname: '玻利维亚',
    ename: 'Bolivia',
    phone_code: '+591',
  },
  {
    id: 155,
    cname: '博内尔岛，圣尤斯特歇斯和',
    ename: 'Bonaire, Sint Eustatius and Saba',
    phone_code: '+599',
  },
  {
    id: 28,
    cname: '波斯尼亚与赫塞哥维纳',
    ename: 'Bosnia and Herzegovina',
    phone_code: '+387',
  },
  {
    id: 29,
    cname: '博茨瓦纳',
    ename: 'Botswana',
    phone_code: '+267',
  },
  {
    id: 30,
    cname: '布维岛',
    ename: 'Bouvet Island',
    phone_code: '+0055',
  },
  {
    id: 31,
    cname: '巴西',
    ename: 'Brazil',
    phone_code: '+55',
  },
  {
    id: 32,
    cname: '英属印度洋领地',
    ename: 'British Indian Ocean Territory',
    phone_code: '+246',
  },
  {
    id: 33,
    cname: '文莱',
    ename: 'Brunei',
    phone_code: '+673',
  },
  {
    id: 34,
    cname: '保加利亚',
    ename: 'Bulgaria',
    phone_code: '+359',
  },
  {
    id: 35,
    cname: '布基纳法索',
    ename: 'Burkina Faso',
    phone_code: '+226',
  },
  {
    id: 36,
    cname: '布隆迪',
    ename: 'Burundi',
    phone_code: '+257',
  },
  {
    id: 37,
    cname: '柬埔寨',
    ename: 'Cambodia',
    phone_code: '+855',
  },
  {
    id: 38,
    cname: '喀麦隆',
    ename: 'Cameroon',
    phone_code: '+237',
  },
  {
    id: 39,
    cname: '加拿大',
    ename: 'Canada',
    phone_code: '+1',
  },
  {
    id: 40,
    cname: '佛得角',
    ename: 'Cape Verde',
    phone_code: '+238',
  },
  {
    id: 41,
    cname: '开曼群岛',
    ename: 'Cayman Islands',
    phone_code: '+1-345',
  },
  {
    id: 42,
    cname: '中非共和国',
    ename: 'Central African Republic',
    phone_code: '+236',
  },
  {
    id: 43,
    cname: '查德',
    ename: 'Chad',
    phone_code: '+235',
  },
  {
    id: 44,
    cname: '智利',
    ename: 'Chile',
    phone_code: '+56',
  },
  {
    id: 45,
    cname: '中国大陆',
    ename: 'China',
    phone_code: '+86',
  },
  {
    id: 46,
    cname: '圣诞岛',
    ename: 'Christmas Island',
    phone_code: '+61',
  },
  {
    id: 47,
    cname: '科科斯基林群岛',
    ename: 'Cocos (Keeling) Islands',
    phone_code: '+61',
  },
  {
    id: 48,
    cname: '哥伦比亚',
    ename: 'Colombia',
    phone_code: '+57',
  },
  {
    id: 49,
    cname: '科摩罗',
    ename: 'Comoros',
    phone_code: '+269',
  },
  {
    id: 50,
    cname: '刚果共和国',
    ename: 'Congo',
    phone_code: '+242',
  },
  {
    id: 51,
    cname: '刚果民主共和国',
    ename: 'Congo The Democratic Republic Of The',
    phone_code: '+243',
  },
  {
    id: 52,
    cname: '库克群岛',
    ename: 'Cook Islands',
    phone_code: '+682',
  },
  {
    id: 53,
    cname: '哥斯达黎加',
    ename: 'Costa Rica',
    phone_code: '+506',
  },
  {
    id: 54,
    cname: '科特迪瓦',
    ename: "Cote D'Ivoire (Ivory Coast)",
    phone_code: '+225',
  },
  {
    id: 55,
    cname: '克罗地亚',
    ename: 'Croatia (Hrvatska)',
    phone_code: '+385',
  },
  {
    id: 56,
    cname: '古巴',
    ename: 'Cuba',
    phone_code: '+53',
  },
  {
    id: 249,
    cname: '库拉索',
    ename: 'Curaçao',
    phone_code: '+599',
  },
  {
    id: 57,
    cname: '塞浦路斯',
    ename: 'Cyprus',
    phone_code: '+357',
  },
  {
    id: 58,
    cname: '捷克',
    ename: 'Czech Republic',
    phone_code: '+420',
  },
  {
    id: 59,
    cname: '丹麦',
    ename: 'Denmark',
    phone_code: '+45',
  },
  {
    id: 60,
    cname: '吉布提',
    ename: 'Djibouti',
    phone_code: '+253',
  },
  {
    id: 61,
    cname: '多米尼克国',
    ename: 'Dominica',
    phone_code: '+1-767',
  },
  {
    id: 62,
    cname: '多米尼加共和国',
    ename: 'Dominican Republic',
    phone_code: '+1-809 and 1-829',
  },
  {
    id: 63,
    cname: '东帝汶',
    ename: 'East Timor',
    phone_code: '+670',
  },
  {
    id: 64,
    cname: '厄瓜多尔',
    ename: 'Ecuador',
    phone_code: '+593',
  },
  {
    id: 65,
    cname: '埃及',
    ename: 'Egypt',
    phone_code: '+20',
  },
  {
    id: 66,
    cname: '萨尔瓦多',
    ename: 'El Salvador',
    phone_code: '+503',
  },
  {
    id: 67,
    cname: '赤道几内亚',
    ename: 'Equatorial Guinea',
    phone_code: '+240',
  },
  {
    id: 68,
    cname: '厄立特里亚',
    ename: 'Eritrea',
    phone_code: '+291',
  },
  {
    id: 69,
    cname: '爱沙尼亚',
    ename: 'Estonia',
    phone_code: '+372',
  },
  {
    id: 70,
    cname: '埃塞俄比亚',
    ename: 'Ethiopia',
    phone_code: '+251',
  },
  {
    id: 71,
    cname: '福克兰群岛',
    ename: 'Falkland Islands',
    phone_code: '+500',
  },
  {
    id: 72,
    cname: '法罗群岛',
    ename: 'Faroe Islands',
    phone_code: '+298',
  },
  {
    id: 73,
    cname: '斐济群岛',
    ename: 'Fiji Islands',
    phone_code: '+679',
  },
  {
    id: 74,
    cname: '芬兰',
    ename: 'Finland',
    phone_code: '+358',
  },
  {
    id: 75,
    cname: '法国',
    ename: 'France',
    phone_code: '+33',
  },
  {
    id: 76,
    cname: '法属圭亚那',
    ename: 'French Guiana',
    phone_code: '+594',
  },
  {
    id: 77,
    cname: '法属波利尼西亚',
    ename: 'French Polynesia',
    phone_code: '+689',
  },
  {
    id: 78,
    cname: '法属南部领土',
    ename: 'French Southern Territories',
    phone_code: '+262',
  },
  {
    id: 79,
    cname: '加蓬',
    ename: 'Gabon',
    phone_code: '+241',
  },
  {
    id: 80,
    cname: '冈比亚',
    ename: 'Gambia The',
    phone_code: '+220',
  },
  {
    id: 81,
    cname: '乔治亚',
    ename: 'Georgia',
    phone_code: '+995',
  },
  {
    id: 82,
    cname: '德国',
    ename: 'Germany',
    phone_code: '+49',
  },
  {
    id: 83,
    cname: '加纳',
    ename: 'Ghana',
    phone_code: '+233',
  },
  {
    id: 84,
    cname: '直布罗陀',
    ename: 'Gibraltar',
    phone_code: '+350',
  },
  {
    id: 85,
    cname: '希腊',
    ename: 'Greece',
    phone_code: '+30',
  },
  {
    id: 86,
    cname: '格陵兰',
    ename: 'Greenland',
    phone_code: '+299',
  },
  {
    id: 87,
    cname: '格林纳达',
    ename: 'Grenada',
    phone_code: '+1-473',
  },
  {
    id: 88,
    cname: '瓜德罗普岛',
    ename: 'Guadeloupe',
    phone_code: '+590',
  },
  {
    id: 89,
    cname: '关岛',
    ename: 'Guam',
    phone_code: '+1-671',
  },
  {
    id: 90,
    cname: '危地马拉',
    ename: 'Guatemala',
    phone_code: '+502',
  },
  {
    id: 91,
    cname: '根西岛和奥尔德尼岛',
    ename: 'Guernsey and Alderney',
    phone_code: '+44-1481',
  },
  {
    id: 92,
    cname: '几内亚',
    ename: 'Guinea',
    phone_code: '+224',
  },
  {
    id: 93,
    cname: '几内亚比绍',
    ename: 'Guinea-Bissau',
    phone_code: '+245',
  },
  {
    id: 94,
    cname: '圭亚那',
    ename: 'Guyana',
    phone_code: '+592',
  },
  {
    id: 95,
    cname: '海地',
    ename: 'Haiti',
    phone_code: '+509',
  },
  {
    id: 96,
    cname: '赫德岛和麦克唐纳群岛',
    ename: 'Heard Island and McDonald Islands',
    phone_code: '+672',
  },
  {
    id: 97,
    cname: '洪都拉斯',
    ename: 'Honduras',
    phone_code: '+504',
  },
  {
    id: 98,
    cname: '香港 (中华人民共和国)',
    ename: 'Hong Kong, China',
    phone_code: '+852',
  },
  {
    id: 99,
    cname: '匈牙利',
    ename: 'Hungary',
    phone_code: '+36',
  },
  {
    id: 100,
    cname: '冰岛',
    ename: 'Iceland',
    phone_code: '+354',
  },
  {
    id: 101,
    cname: '印度',
    ename: 'India',
    phone_code: '+91',
  },
  {
    id: 102,
    cname: '印度尼西亚',
    ename: 'Indonesia',
    phone_code: '+62',
  },
  {
    id: 103,
    cname: '伊朗',
    ename: 'Iran',
    phone_code: '+98',
  },
  {
    id: 104,
    cname: '伊拉克',
    ename: 'Iraq',
    phone_code: '+964',
  },
  {
    id: 105,
    cname: '爱尔兰',
    ename: 'Ireland',
    phone_code: '+353',
  },
  {
    id: 106,
    cname: '以色列',
    ename: 'Israel',
    phone_code: '+972',
  },
  {
    id: 107,
    cname: '意大利',
    ename: 'Italy',
    phone_code: '+39',
  },
  {
    id: 108,
    cname: '牙买加',
    ename: 'Jamaica',
    phone_code: '+1-876',
  },
  {
    id: 109,
    cname: '日本',
    ename: 'Japan',
    phone_code: '+81',
  },
  {
    id: 110,
    cname: '泽西岛',
    ename: 'Jersey',
    phone_code: '+44-1534',
  },
  {
    id: 111,
    cname: '约旦',
    ename: 'Jordan',
    phone_code: '+962',
  },
  {
    id: 112,
    cname: '哈萨克斯坦',
    ename: 'Kazakhstan',
    phone_code: '+7',
  },
  {
    id: 113,
    cname: '肯尼亚',
    ename: 'Kenya',
    phone_code: '+254',
  },
  {
    id: 114,
    cname: '基里巴斯',
    ename: 'Kiribati',
    phone_code: '+686',
  },
  {
    id: 115,
    cname: '朝鲜',
    ename: 'Korea North',
    phone_code: '+850',
  },
  {
    id: 116,
    cname: '韩国',
    ename: 'Korea South',
    phone_code: '+82',
  },
  {
    id: 248,
    cname: '科索沃',
    ename: 'Kosovo',
    phone_code: '+383',
  },
  {
    id: 117,
    cname: '科威特',
    ename: 'Kuwait',
    phone_code: '+965',
  },
  {
    id: 118,
    cname: '吉尔吉斯斯坦',
    ename: 'Kyrgyzstan',
    phone_code: '+996',
  },
  {
    id: 119,
    cname: '老挝',
    ename: 'Laos',
    phone_code: '+856',
  },
  {
    id: 120,
    cname: '拉脱维亚',
    ename: 'Latvia',
    phone_code: '+371',
  },
  {
    id: 121,
    cname: '黎巴嫩',
    ename: 'Lebanon',
    phone_code: '+961',
  },
  {
    id: 122,
    cname: '莱索托',
    ename: 'Lesotho',
    phone_code: '+266',
  },
  {
    id: 123,
    cname: '利比里亚',
    ename: 'Liberia',
    phone_code: '+231',
  },
  {
    id: 124,
    cname: '利比亚',
    ename: 'Libya',
    phone_code: '+218',
  },
  {
    id: 125,
    cname: '列支敦士登',
    ename: 'Liechtenstein',
    phone_code: '+423',
  },
  {
    id: 126,
    cname: '立陶宛',
    ename: 'Lithuania',
    phone_code: '+370',
  },
  {
    id: 127,
    cname: '卢森堡',
    ename: 'Luxembourg',
    phone_code: '+352',
  },
  {
    id: 128,
    cname: '澳门 (中华人民共和国)',
    ename: 'Macau, China',
    phone_code: '+853',
  },
  {
    id: 129,
    cname: '马其顿',
    ename: 'Macedonia',
    phone_code: '+389',
  },
  {
    id: 130,
    cname: '马达加斯加',
    ename: 'Madagascar',
    phone_code: '+261',
  },
  {
    id: 131,
    cname: '马拉维',
    ename: 'Malawi',
    phone_code: '+265',
  },
  {
    id: 132,
    cname: '马来西亚',
    ename: 'Malaysia',
    phone_code: '+60',
  },
  {
    id: 133,
    cname: '马尔代夫',
    ename: 'Maldives',
    phone_code: '+960',
  },
  {
    id: 134,
    cname: '马里共和国',
    ename: 'Mali',
    phone_code: '+223',
  },
  {
    id: 135,
    cname: '马耳他',
    ename: 'Malta',
    phone_code: '+356',
  },
  {
    id: 136,
    cname: '马恩岛',
    ename: 'Man (Isle of)',
    phone_code: '+44-1624',
  },
  {
    id: 137,
    cname: '马绍尔群岛',
    ename: 'Marshall Islands',
    phone_code: '+692',
  },
  {
    id: 138,
    cname: '马提尼克',
    ename: 'Martinique',
    phone_code: '+596',
  },
  {
    id: 139,
    cname: '毛里塔尼亚',
    ename: 'Mauritania',
    phone_code: '+222',
  },
  {
    id: 140,
    cname: '毛里求斯',
    ename: 'Mauritius',
    phone_code: '+230',
  },
  {
    id: 141,
    cname: '马约特岛',
    ename: 'Mayotte',
    phone_code: '+262',
  },
  {
    id: 142,
    cname: '墨西哥',
    ename: 'Mexico',
    phone_code: '+52',
  },
  {
    id: 143,
    cname: '密克罗尼西亚',
    ename: 'Micronesia',
    phone_code: '+691',
  },
  {
    id: 144,
    cname: '摩尔多瓦',
    ename: 'Moldova',
    phone_code: '+373',
  },
  {
    id: 145,
    cname: '摩纳哥',
    ename: 'Monaco',
    phone_code: '+377',
  },
  {
    id: 146,
    cname: '蒙古国',
    ename: 'Mongolia',
    phone_code: '+976',
  },
  {
    id: 147,
    cname: '黑山共和国',
    ename: 'Montenegro',
    phone_code: '+382',
  },
  {
    id: 148,
    cname: '蒙特塞拉特岛',
    ename: 'Montserrat',
    phone_code: '+1-664',
  },
  {
    id: 149,
    cname: '摩洛哥',
    ename: 'Morocco',
    phone_code: '+212',
  },
  {
    id: 150,
    cname: '莫桑比克',
    ename: 'Mozambique',
    phone_code: '+258',
  },
  {
    id: 151,
    cname: '缅甸',
    ename: 'Myanmar',
    phone_code: '+95',
  },
  {
    id: 152,
    cname: '纳米比亚',
    ename: 'Namibia',
    phone_code: '+264',
  },
  {
    id: 153,
    cname: '瑙鲁',
    ename: 'Nauru',
    phone_code: '+674',
  },
  {
    id: 154,
    cname: '尼泊尔',
    ename: 'Nepal',
    phone_code: '+977',
  },
  {
    id: 156,
    cname: '荷兰',
    ename: 'Netherlands The',
    phone_code: '+31',
  },
  {
    id: 157,
    cname: '新喀里多尼亚',
    ename: 'New Caledonia',
    phone_code: '+687',
  },
  {
    id: 158,
    cname: '新西兰',
    ename: 'New Zealand',
    phone_code: '+64',
  },
  {
    id: 159,
    cname: '尼加拉瓜',
    ename: 'Nicaragua',
    phone_code: '+505',
  },
  {
    id: 160,
    cname: '尼日尔',
    ename: 'Niger',
    phone_code: '+227',
  },
  {
    id: 161,
    cname: '尼日利亚',
    ename: 'Nigeria',
    phone_code: '+234',
  },
  {
    id: 162,
    cname: '纽埃岛',
    ename: 'Niue',
    phone_code: '+683',
  },
  {
    id: 163,
    cname: '诺福克岛',
    ename: 'Norfolk Island',
    phone_code: '+672',
  },
  {
    id: 164,
    cname: '北马里亚纳群岛',
    ename: 'Northern Mariana Islands',
    phone_code: '+1-670',
  },
  {
    id: 165,
    cname: '挪威',
    ename: 'Norway',
    phone_code: '+47',
  },
  {
    id: 166,
    cname: '阿曼',
    ename: 'Oman',
    phone_code: '+968',
  },
  {
    id: 167,
    cname: '巴基斯坦',
    ename: 'Pakistan',
    phone_code: '+92',
  },
  {
    id: 168,
    cname: '帕劳',
    ename: 'Palau',
    phone_code: '+680',
  },
  {
    id: 169,
    cname: '巴勒斯坦领土',
    ename: 'Palestinian Territory Occupied',
    phone_code: '+970',
  },
  {
    id: 170,
    cname: '巴拿马',
    ename: 'Panama',
    phone_code: '+507',
  },
  {
    id: 171,
    cname: '巴布亚新几内亚',
    ename: 'Papua new Guinea',
    phone_code: '+675',
  },
  {
    id: 172,
    cname: '巴拉圭',
    ename: 'Paraguay',
    phone_code: '+595',
  },
  {
    id: 173,
    cname: '秘鲁',
    ename: 'Peru',
    phone_code: '+51',
  },
  {
    id: 174,
    cname: '菲律宾',
    ename: 'Philippines',
    phone_code: '+63',
  },
  {
    id: 175,
    cname: '皮特凯恩岛',
    ename: 'Pitcairn Island',
    phone_code: '+870',
  },
  {
    id: 176,
    cname: '波兰',
    ename: 'Poland',
    phone_code: '+48',
  },
  {
    id: 177,
    cname: '葡萄牙',
    ename: 'Portugal',
    phone_code: '+351',
  },
  {
    id: 178,
    cname: '波多黎各',
    ename: 'Puerto Rico',
    phone_code: '+1-787 and 1-939',
  },
  {
    id: 179,
    cname: '卡达',
    ename: 'Qatar',
    phone_code: '+974',
  },
  {
    id: 180,
    cname: '留尼汪',
    ename: 'Reunion',
    phone_code: '+262',
  },
  {
    id: 181,
    cname: '罗马尼亚',
    ename: 'Romania',
    phone_code: '+40',
  },
  {
    id: 182,
    cname: '俄罗斯',
    ename: 'Russia',
    phone_code: '+7',
  },
  {
    id: 183,
    cname: '卢旺达',
    ename: 'Rwanda',
    phone_code: '+250',
  },
  {
    id: 184,
    cname: '圣赫勒拿',
    ename: 'Saint Helena',
    phone_code: '+290',
  },
  {
    id: 185,
    cname: '圣基茨和尼维斯',
    ename: 'Saint Kitts And Nevis',
    phone_code: '+1-869',
  },
  {
    id: 186,
    cname: '圣卢西亚',
    ename: 'Saint Lucia',
    phone_code: '+1-758',
  },
  {
    id: 187,
    cname: '圣皮埃尔和密克隆',
    ename: 'Saint Pierre and Miquelon',
    phone_code: '+508',
  },
  {
    id: 188,
    cname: '圣文森特和格林纳丁斯',
    ename: 'Saint Vincent And The Grenadines',
    phone_code: '+1-784',
  },
  {
    id: 189,
    cname: '圣巴瑟米',
    ename: 'Saint-Barthelemy',
    phone_code: '+590',
  },
  {
    id: 190,
    cname: '圣马丁岛(荷兰部分)',
    ename: 'Saint-Martin (French part)',
    phone_code: '+590',
  },
  {
    id: 191,
    cname: '萨摩亚',
    ename: 'Samoa',
    phone_code: '+685',
  },
  {
    id: 192,
    cname: '圣马力诺',
    ename: 'San Marino',
    phone_code: '+378',
  },
  {
    id: 193,
    cname: '圣多美普林西比',
    ename: 'Sao Tome and Principe',
    phone_code: '+239',
  },
  {
    id: 194,
    cname: '沙特阿拉伯',
    ename: 'Saudi Arabia',
    phone_code: '+966',
  },
  {
    id: 195,
    cname: '塞内加尔',
    ename: 'Senegal',
    phone_code: '+221',
  },
  {
    id: 196,
    cname: 'Serbia',
    ename: 'Serbia',
    phone_code: '+381',
  },
  {
    id: 197,
    cname: '塞舌尔',
    ename: 'Seychelles',
    phone_code: '+248',
  },
  {
    id: 198,
    cname: '塞拉利昂',
    ename: 'Sierra Leone',
    phone_code: '+232',
  },
  {
    id: 199,
    cname: '新加坡',
    ename: 'Singapore',
    phone_code: '+65',
  },
  {
    id: 250,
    cname: '荷属圣马丁',
    ename: 'Sint Maarten (Dutch part)',
    phone_code: '+1721',
  },
  {
    id: 200,
    cname: '斯洛伐克',
    ename: 'Slovakia',
    phone_code: '+421',
  },
  {
    id: 201,
    cname: '斯洛文尼亚',
    ename: 'Slovenia',
    phone_code: '+386',
  },
  {
    id: 202,
    cname: '所罗门群岛',
    ename: 'Solomon Islands',
    phone_code: '+677',
  },
  {
    id: 203,
    cname: '索马里',
    ename: 'Somalia',
    phone_code: '+252',
  },
  {
    id: 204,
    cname: '南非',
    ename: 'South Africa',
    phone_code: '+27',
  },
  {
    id: 205,
    cname: '南乔治亚岛',
    ename: 'South Georgia',
    phone_code: '+00',
  },
  {
    id: 206,
    cname: '南苏丹',
    ename: 'South Sudan',
    phone_code: '+211',
  },
  {
    id: 207,
    cname: '西班牙',
    ename: 'Spain',
    phone_code: '+34',
  },
  {
    id: 208,
    cname: '斯里兰卡',
    ename: 'Sri Lanka',
    phone_code: '+94',
  },
  {
    id: 209,
    cname: '苏丹',
    ename: 'Sudan',
    phone_code: '+249',
  },
  {
    id: 210,
    cname: '苏里南',
    ename: 'Suriname',
    phone_code: '+597',
  },
  {
    id: 211,
    cname: '斯瓦尔巴群岛',
    ename: 'Svalbard And Jan Mayen Islands',
    phone_code: '+47',
  },
  {
    id: 212,
    cname: '斯威士兰',
    ename: 'Swaziland',
    phone_code: '+268',
  },
  {
    id: 213,
    cname: '瑞典',
    ename: 'Sweden',
    phone_code: '+46',
  },
  {
    id: 214,
    cname: '瑞士',
    ename: 'Switzerland',
    phone_code: '+41',
  },
  {
    id: 215,
    cname: '叙利亚',
    ename: 'Syria',
    phone_code: '+963',
  },
  {
    id: 216,
    cname: '台湾（中华人民共和国省级行政区）',
    ename: 'Taiwan, China',
    phone_code: '+886',
  },
  {
    id: 217,
    cname: '塔吉克',
    ename: 'Tajikistan',
    phone_code: '+992',
  },
  {
    id: 218,
    cname: '坦桑尼亚',
    ename: 'Tanzania',
    phone_code: '+255',
  },
  {
    id: 219,
    cname: '泰国',
    ename: 'Thailand',
    phone_code: '+66',
  },
  {
    id: 220,
    cname: '多哥',
    ename: 'Togo',
    phone_code: '+228',
  },
  {
    id: 221,
    cname: '托克劳群岛',
    ename: 'Tokelau',
    phone_code: '+690',
  },
  {
    id: 222,
    cname: '东加',
    ename: 'Tonga',
    phone_code: '+676',
  },
  {
    id: 223,
    cname: '特立尼达和多巴哥',
    ename: 'Trinidad And Tobago',
    phone_code: '+1-868',
  },
  {
    id: 224,
    cname: '突尼斯',
    ename: 'Tunisia',
    phone_code: '+216',
  },
  {
    id: 225,
    cname: '土耳其',
    ename: 'Turkey',
    phone_code: '+90',
  },
  {
    id: 226,
    cname: '土库曼',
    ename: 'Turkmenistan',
    phone_code: '+993',
  },
  {
    id: 227,
    cname: '特克斯和凯科斯群岛',
    ename: 'Turks And Caicos Islands',
    phone_code: '+1-649',
  },
  {
    id: 228,
    cname: '图瓦卢',
    ename: 'Tuvalu',
    phone_code: '+688',
  },
  {
    id: 229,
    cname: '乌干达',
    ename: 'Uganda',
    phone_code: '+256',
  },
  {
    id: 230,
    cname: '乌克兰',
    ename: 'Ukraine',
    phone_code: '+380',
  },
  {
    id: 231,
    cname: '阿拉伯联合酋长国',
    ename: 'United Arab Emirates',
    phone_code: '+971',
  },
  {
    id: 232,
    cname: '英国',
    ename: 'United Kingdom',
    phone_code: '+44',
  },
  {
    id: 233,
    cname: '美国',
    ename: 'United States',
    phone_code: '+1',
  },
  {
    id: 234,
    cname: '美属边疆群岛',
    ename: 'United States Minor Outlying Islands',
    phone_code: '+1',
  },
  {
    id: 235,
    cname: '乌拉圭',
    ename: 'Uruguay',
    phone_code: '+598',
  },
  {
    id: 236,
    cname: '乌兹别克斯坦',
    ename: 'Uzbekistan',
    phone_code: '+998',
  },
  {
    id: 237,
    cname: '瓦努阿图',
    ename: 'Vanuatu',
    phone_code: '+678',
  },
  {
    id: 238,
    cname: '梵蒂冈',
    ename: 'Vatican City State (Holy See)',
    phone_code: '+379',
  },
  {
    id: 239,
    cname: '委内瑞拉',
    ename: 'Venezuela',
    phone_code: '+58',
  },
  {
    id: 240,
    cname: '越南',
    ename: 'Vietnam',
    phone_code: '+84',
  },
  {
    id: 241,
    cname: '英属维尔京群岛',
    ename: 'Virgin Islands (British)',
    phone_code: '+1-284',
  },
  {
    id: 242,
    cname: '美属维尔京群岛',
    ename: 'Virgin Islands (US)',
    phone_code: '+1-340',
  },
  {
    id: 243,
    cname: '瓦利斯和富图纳群岛',
    ename: 'Wallis And Futuna Islands',
    phone_code: '+681',
  },
  {
    id: 244,
    cname: '西撒哈拉',
    ename: 'Western Sahara',
    phone_code: '+212',
  },
  {
    id: 245,
    cname: '也门',
    ename: 'Yemen',
    phone_code: '+967',
  },
  {
    id: 246,
    cname: '赞比亚',
    ename: 'Zambia',
    phone_code: '+260',
  },
  {
    id: 247,
    cname: '津巴布韦',
    ename: 'Zimbabwe',
    phone_code: '+263',
  },
]
